version: "3.1"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myRootPassword
      MYSQL_USER: development
      MYSQL_PASSWORD: development
      MYSQL_DATABASE: task_mate
    ports:
      - 3306:3306
